name: editor
description: "A new Flutter project."
publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.4.2
  gap: ^3.0.1
  bounce: ^1.0.2
  motion: ^2.0.1
  universal_io: ^2.2.2
  adaptive_theme: ^3.7.0
  go_router: ^14.6.3
  flutter_code_editor: ^0.3.2
  cross_file: ^0.3.4+2
  hydrated_bloc: ^10.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  logger: ^2.5.0
  widget_arrows: ^0.6.0
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  webview_flutter: ^4.10.0
  flutter_chat_ui: ^1.6.15
  openai_dart: ^0.4.5
  yaml: ^3.1.3
  http: ^1.3.0
  open_file_macos: ^0.1.0
  lucide_icons_flutter: ^1.2.6
  flutter_chat_types: ^3.6.2
  multi_split_view: ^3.6.0
  window_manager: ^0.4.3
  auto_updater: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  package_rename_plus: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  
flutter:
  uses-material-design: true

scripts:
  init: |
    dart run package_rename_plus
    dart run flutter_launcher_icons
  gen: |
    dart run build_runner build --delete-conflicting-outputs
    dart run slang
  slang: "dart run slang"
  imports: "dart run import_sorter:main"
  rename: "dart run package_rename_plus"
  icon: "dart run flutter_launcher_icons"
  web: "flutter run -d chrome --web-port 5173"
  watch: "flutter pub run build_runner watch --delete-conflicting-outputs"
  add: "flutter pub add"
  macos: "flutter run -d macos"
