name: teta_oss
description: "Teta OSS Desktop App"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  editor:
    path: ../../pkgs/teta_editor
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  adaptive_theme: ^3.7.0
  uuid: ^4.5.1
  hydrated_bloc: ^10.0.0
  window_manager: ^0.4.3
  path_provider: ^2.1.5
  hive: ^2.2.3
  go_router: ^14.7.1
  envied: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  package_rename_plus: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  envied_generator: ^1.1.0

flutter:
  uses-material-design: true
  assets: 
    - .env
    - assets/wanted-sans/
    - assets/

  fonts:
    - family: Wanted Sans
      fonts:
        - asset: assets/wanted-sans/WantedSans-Regular.ttf
          weight: 400
        - asset: assets/wanted-sans/WantedSans-Medium.ttf
          weight: 500
        - asset: assets/wanted-sans/WantedSans-SemiBold.ttf
          weight: 600
        - asset: assets/wanted-sans/WantedSans-Bold.ttf
          weight: 700
        - asset: assets/wanted-sans/WantedSans-ExtraBold.ttf
          weight: 800
        - asset: assets/wanted-sans/WantedSans-Black.ttf
          weight: 900

scripts:
  init: |
    dart run package_rename_plus
    dart run flutter_launcher_icons
  gen: |
    dart run build_runner build --delete-conflicting-outputs
  slang: "dart run slang"
  imports: "dart run import_sorter:main"
  rename: "dart run package_rename_plus"
  icon: "dart run flutter_launcher_icons"
  web: "flutter run -d chrome --web-port 5173"
  watch: "flutter pub run build_runner watch --delete-conflicting-outputs"
  add: "flutter pub add"
  macos: "flutter run -d macos"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo_macos.png"

package_rename_config:
  android:
    app_name: "Teta"
    package_name: "com.andreabuttarelli.dazero"
  ios:
    app_name: "Teta"
    bundle_name: "com.andreabuttarelli.dazero"
    package_name: "com.andreabuttarelli.dazero"
  linux:
    app_name: "Teta"
    package_name: "com.andreabuttarelli.dazero"
    exe_name: "Teta"
  macos:
    app_name: "Teta"
    package_name: "com.andreabuttarelli.dazero"
    copyright_notice: "© 2024 Andrea Buttarelli"
  web:
    app_name: "Teta"
    description: "Your app description..."
  windows:
    app_name: "com.andreabuttarelli.dazero"
    organization: "Andrea Buttarelli"
    copyright_notice: "© 2024 Andrea Buttarelli"
    exe_name: "Teta"
